### ISSUE TITLE
Lab 4: add --ignore

### ISSUE THREAD

**Issue by TDDR** [MLJBrackett/link-check#7]
Hello @MLJBrackett 

I'm gonna be adding the following feature for lab4 to your repository!

The --ignore, -i, \i flag is optional, and if present should take a filepath and use it to load and parse an ignored URLs text file. If the ignore file isn't found, give an appropriate error message. Otherwise, all URLs should be checked against this list to see if they need to be ignored.

**Comment by MLJBrackett** [comment]
Thanks! Ill assign you.

**Comment by TDDR** [comment]
Hey @MLJBrackett,

Here's the [location](https://github.com/TDDR/link-check/tree/issue-7) of my branch.
I'm finished with it so please let me know if want me to make any changes.

**Comment by MLJBrackett** [comment]
Looks good, I've merged it.
